# Generated by Django 2.0.3 on 2018-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/items', verbose_name='Imagen del articulo'),
        ),
    ]
